[tool.black]
line-length = 88
include = '(\.pyi?$|\.spec$)'
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | buildozer\.spec
)
'''

[tool.isort]
line_length = 88
include_trailing_comma = true
multi_line_output = 3
use_parentheses = true
force_grid_wrap = 0
ensure_newline_before_comments = true
known_third_party = ["setuptools", "kivy", "requests", "PIL", "android", "jnius", "watchdog", "sphinx", "docutils", "autoapi", "unidecode"]